version: "3"

services:
  nginx:
    container_name: xiaobingvue
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    #   - 443:443
    volumes:
      - ./nginx/log:/var/log/nginx
      - ./dist/:/usr/share/nginx/html/
      - ./admin/:/usr/share/nginx/html/admin/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    command: /bin/bash -c "nginx -g 'daemon off;'"
